<?php

$modversion['name'] = _MI_GS_NAME;
$modversion['version'] = 2.0;
$modversion['description'] = _MI_GS_DESC;
$modversion['credits'] = 'E-Xoops France<br>http://www.e-xoopsfr.com';
$modversion['author'] = 'Olivier Duffez<br>Googlestats ( http://www.googlestats.com/ )';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'images/logo.gif';
$modversion['dirname'] = 'googlestats';
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'gs_log';
$modversion['tables'][1] = 'gs_robots';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';
// Menu
$modversion['hasMain'] = 1;
